### ISSUE TITLE
Kompatibilitet med eksisterende API

### ISSUE THREAD

**Issue by eriweb** [telemark/konkurranse-utviklingstjenester#1]
Hei,
dere skriver:

> Du står fritt til å designe APIet, men det skal kunne oppfylle de samme funksjonene som våre eksisterende APIer for ansatte og virksomheter
> Definisjon av samme funksjonalitet er opp til deg.

Er det slik å forstå at vi kan endre syntaks, parametre og eventuelt returmåte?

**Comment by zrrrzzt** [comment]
@terbolous Det er korrekt!
